# Generated by Django 4.2.1 on 2023-05-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FIC', 'FICTION'), ('POL', 'POLITICS'), ('FIN', 'FINANCE'), ('ROM', 'ROMANCE')], max_length=15),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('Y', 'YORUBA'), ('E', 'ENGLISH'), ('H', 'HAUSA'), ('I', 'IGBO')], max_length=15),
        ),
    ]
